js4再提出
chillout2san/work_js4 pull request #4
Opened 2021-02-08 04:10 UTC by chillout2san

2021-02-08 11:24 UTC, myzktkyk requested changes
まず動作については問題ありませんでした。
コードについては何点か指摘をしておりますので、指摘箇所をご確認ください。

その他の指摘点としては Pull Request の扱い方がちょっと気になりました。
レビューを依頼するたびに前の Pull Request を Close して新しく Pull Request を作られているようですが
実際の業務ではそのような使い方をすることはまずありません。
以下のような流れになることが多いです。

1. Pull Request で指摘を受ける
2. その指摘をコードに反映し Commit/Push 
3. 指摘のコメントに対して「このように修正しました」とコメントを Reply する

Pull Request を Close するのは「修正方針がそもそも間違っている」「仕様理解に誤りがあった」など
大きな認識齟齬があった場合に「取り消し」の為に使うことが多いです。

2021-02-08 11:24 UTC, myzktkyk commented on main.js
> +  getQuizData();
`getQuizData` は `async` なので呼び出す際は `await` を付けて呼び出してください。
```suggestion
  await getQuizData();
```

2021-02-08 11:24 UTC, myzktkyk commented on main.js
> +  }catch(error) {
インデントが不自然にずれてしまっているようです。

```suggestion
    } catch(error) {
```

2021-02-09 04:45 UTC, chillout2san commented on main.js
> +  getQuizData();
コードレビュー、プルリクの指摘ありがとうございます！

このように修正いたしました。

https://github.com/chillout2san/work_js4/blob/d60c0d2affca023e1353072643398fe4a9fddb7c/main.js#L37-L43

ちなみに非同期処理があまり理解できていないなと感じ、色々実験しておりました。
await getQuizData();を39行目に置き、「開始」ボタンを押下すると、「取得中」の画面に切り替わらず、そのままクイズ出題されました。

こちらはgetQuizData();が大して重い処理ではなかったために、「**取得中」の画面に切り替わっているが、見えなかった**という理解でよいでしょうか。

宜しくお願いいたします。

2021-02-09 04:46 UTC, chillout2san commented on main.js
> +  }catch(error) {
失礼いたしました。
修正いたしました！

https://github.com/chillout2san/work_js4/blob/d60c0d2affca023e1353072643398fe4a9fddb7c/main.js#L95-L96

2021-02-14 05:34 UTC, closed without merging